version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the whole project for live development
      - ./hr_streamline_app.db:/app/hr_streamline_app.db  # Persist SQLite database
    env_file: .env
    environment:
      - CONFIG_CLASS=config.DevelopmentConfig
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
      - ./hr_streamline_app.db:/app/hr_streamline_app.db
    env_file: .env
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A celery_worker.celery beat --loglevel=info
    volumes:
      - .:/app
      - ./hr_streamline_app.db:/app/hr_streamline_app.db
    env_file: .env
    depends_on:
      - redis
